= GroovyFx
:version: 9.0.0-SNAPSHOT
:project-name: groovyfx
:branch: master

image:http://img.shields.io/travis/groovyfx-project/{project-name}/{branch}.svg["Build Status", link="https://travis-ci.org/groovyfx-project/{project-name}"]
image:http://img.shields.io/coveralls/groovyfx-project/{project-name}/{branch}.svg["Coverage Status", link="https://coveralls.io/r/groovyfx-project/{project-name}"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

== Build instructions

Download JavaFX from http://javafx.com and follow the install instructions.

Or if you are feeling "bleeding edge" clone the Git repository!


=== Building with Gradle shell command line

* Make sure you have Java8u20 (or greater) installed
* cd to the GroovyFX directory
* gradlew build

To run any specific demo, e.g. the AccordionDemo, you can just call:

[source]
----
gradlew AccordionDemo
----

To see an executable overview of all build tasks including all demos:

[source]
----
gradlew --gui
----

== Using GroovyFX from Maven Central

Having GroovyFX in Maven Central (thanks to Sonatype's OSS hosting) makes it simple to use GroovyFX in
everything from simple test scripts to larger projects.  The Maven coordinates are as follows:

* _groupId_: org.codehaus.groovyfx
* _artifactId_: groovyfx
* _version_: {version}

GroovyFX is simple to include in Groovy scripts thanks to Groovy's Grab annotation, a part of the Grape
system.  Just include the following line at the top of your script:

[source]
[subs="attributes"]
----
@Grab('org.codehaus.groovyfx:groovyfx:{version})
----

You may find that when you start such a script, you have to ensure that an explicit reference to your
jfxrt.jar is declared in your classpath. For Java 8:

[source]
----
groovy -cp $JAVA_HOME/jre/lib/ext/jfxrt.jar myScript.groovy
----

== Creating a GroovyFX-Based Project with Gradle

It is also simple to set up your own GroovyFX-based project using Gradle as the build system.  This sample
link:https://gist.github.com/2712927[build.gradle] script will get you started.

Just create a new directory for your project and place the Gradle script into it.  Then simply execute the
following command:

[source]
[subs="attributes"]
----
gradle makeDirs
----

to set up the rest of your project's directory structure.  You will automatically have a dependency on both
Groovy and GroovyFX.

== Building with IntelliJ IDEA

GroovyFX's build script is capable of generating all of the project files necessary to build the project
with IntelliJ IDEA.  Just run the following command from the project's root directory:

[source]
----
gradlew idea
----

This will generate a groovyfx.ipr file.  From IntelliJ IDEA, select File -> Open Project and navigate to the
directory containing the groovyfx.ipr file and open it.  You should now be able to build the library and run
the demos with IntelliJ IDEA.

== Building with NetBeans

Install the NetBeans Gradle Plugin (which should be in the list of plugins offered as standard, but failing
that there see link:http://plugins.netbeans.org/plugin/44510/gradle-support[]). Using the open a new project
dialogue, navigate to the GroovyFX project directory and you should see the Gradle logo indicating you can
open this as a Gradle project. You should now be able to build the library and run the demos with NetBeans.

== Building with Eclipse

Install the Gradle BuildShip and The Groovy Eclipse plugins form the Eclipse Marketplace to get started.
