= GroovyFx
:linkattrs:
:branch: master
:project-owner:   groovyfx-project
:project-name:    groovyfx
:project-group:   org.groovyfx
:project-version: 11.0.0-SNAPSHOT

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:https://github.com/{project-owner}/{project-name}/workflows/Build/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg?label=maven[link="https://search.maven.org/#search|ga|1|{project-group}"]

== Build instructions

=== Building with Gradle shell command line

* Make sure you have Java 11 (or greater) installed
* cd to the GroovyFX directory
* gradlew build

To run any specific demo, e.g. the AccordionDemo, you can just call:

[source]
----
gradlew runAccordionDemo
----

== Using GroovyFX from Maven Central or Bintray

Having GroovyFX in Bintray and Maven Central (thanks to Sonatype's OSS hosting) makes it simple to use GroovyFX in
everything from simple test scripts to larger projects. The Maven coordinates are as follows:

* _groupId_: org.groovyfx
* _artifactId_: groovyfx
* _version_: {version}

GroovyFX is simple to include in Groovy scripts thanks to Groovy's Grab annotation, a part of the Grape
system.  Just include the following line at the top of your script:

[source]
[subs="attributes"]
----
@Grab('org.groovyfx:groovyfx:{version}')
----

== Creating a GroovyFX-Based Project with Gradle

It is also simple to set up your own GroovyFX-based project using Gradle as the build system.  This sample
link:https://gist.github.com/2712927[build.gradle] script will get you started.

Just create a new directory for your project and place the Gradle script into it.  Then simply execute the
following command:

[source]
[subs="attributes"]
----
gradle makeDirs
----

to set up the rest of your project's directory structure.  You will automatically have a dependency on both
Groovy and GroovyFX.

== Building with IntelliJ IDEA

GroovyFX's build script is capable of generating all of the project files necessary to build the project
with IntelliJ IDEA.  Just run the following command from the project's root directory:

[source]
----
gradlew idea
----

This will generate a groovyfx.ipr file.  From IntelliJ IDEA, select File -> Open Project and navigate to the
directory containing the groovyfx.ipr file and open it.  You should now be able to build the library and run
the demos with IntelliJ IDEA.

== Building with NetBeans

Install the NetBeans Gradle Plugin (which should be in the list of plugins offered as standard, but failing
that there see link:http://plugins.netbeans.org/plugin/44510/gradle-support[]). Using the open a new project
dialogue, navigate to the GroovyFX project directory and you should see the Gradle logo indicating you can
open this as a Gradle project. You should now be able to build the library and run the demos with NetBeans.

== Building with Eclipse

Install the Gradle BuildShip and The Groovy Eclipse plugins form the Eclipse Marketplace to get started.
